name: Renovate

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
      configurationFile: 
        description: "Override default configuration file"
        required: false
        default: ".github/renovate.json"
        type: string
      renovate-version: 
        description: "Override default renovate version"
        required: false
        default: "full"
        type: string
  workflow_call:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
      configurationFile: 
        description: "Override default configuration file"
        required: false
        default: ".github/renovate.json"
        type: string
      renovate-version: 
        description: "Override default renovate version"
        required: false
        default: "full"
        type: string

concurrency: renovate

env:
  NODE_VERSION: "22"
  RENOVATE_VERSION: "39.82.1" # tbd
  RENOVATE_ASSIGNES: "marcoschmidl"
  # Github read-only PAT for Releases
  GITHUB_COM_TOKEN: ${{ secrets.PAT_GITHUB_RELEASES_RENOVATE}}
  # Repository taken from variable to keep configuration file generic
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  # Onboarding not needed for self hosted
  RENOVATE_ONBOARDING: "false" 
  # Username for GitHub authentication (should match GitHub App name + [bot])
  RENOVATE_USERNAME: "renovate-rancher[bot]"
  # Git commit author used, must match GitHub App
  RENOVATE_GIT_AUTHOR: "renovate-rancher <119870437+renovate-rancher[bot]@users.noreply.github.com>"
  # Use GitHub API to create commits (this allows for signed commits from GitHub App)
  RENOVATE_PLATFORM_COMMIT: "false"
  RENOVATE_CONFIG_FILE: ${{ inputs.configurationFile }}
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      # - name: Validate and printout config
      #   run: jq -e . "${RENOVATE_CONFIG_FILE}"       
      # - name: Install Node
      #   uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      #   with:
      #     node-version: ${{ inputs.node-version }}
      # - name: Validate Renovate JS 
      #   run: npx -v
        # run: npx --yes --package renovate -- renovate-config-validator --strict
        # run: npx --yes --package renovate -- renovate-config-validator --strict
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e1db501385ddcccbaae6fb9c06befae04f379f23 # v40.2.10
        with:
          renovate-version: ${{ env.RENOVATE_VERSION }}
          configurationFile: ${{ env.RENOVATE_CONFIG_FILE }}
          token: "${{ secrets.RENOVATE_TOKEN }}"